---
# PGP keys for external repositories
pgp_keys:
- url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  keyring: /usr/share/keyrings/cloud.google.gpg
- url: https://download.docker.com/linux/debian/gpg
  keyring:
- url: https://apt.releases.hashicorp.com/gpg
  keyring:

# apt repositories
debian_10_apt_repositories:
- repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
  state: present
- repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
  state: present
- repo: deb [arch=amd64] https://apt.releases.hashicorp.com buster main
  state: present

# apt packages
precondition_apt_packages:
- name: apt-transport-https
  state: latest
- name: ca-certificates
  state: latest
- name: gnupg
  state: latest
- name: gnupg-agent
  state: latest
- name: wget
  state: latest
- name: curl
  state: latest
- name: unzip
  state: latest
- name: software-properties-common
  state: latest

docker_removal_apt_package:
- name: docker
- name: docker-engine
- name: docker.io
- name: containerd
- name: runc

basic_apt_packages:
- name: git
  state: latest
- name: zsh
  state: latest
- name: build-essential
  state: latest
- name: libssl-dev
  state: latest
- name: zlib1g-dev
  state: latest
- name: libbz2-dev
  state: latest
- name: libreadline-dev
  state: latest
- name: libffi-dev
  state: latest
- name: emacs
  state: latest
- name: vim
  state: latest
- name: python3
  state: latest
- name: python3-pip
  state: latest
- name: python3-venv
  state: latest
- name: tmux
  state: latest
- name: jq
  state: latest
- name: fzf
  state: latest
- name: fd-find
  state: latest
- name: silversearcher-ag
  state: latest
- name: sysstat
  state: latest
- name: htop
  state: latest
- name: atop
  state: latest
- name: nethogs
  state: latest
- name: vnstat
  state: latest
- name: nmon
  state: latest
- name: xclip
  state: latest
- name: google-cloud-sdk
  state: latest
- name: google-cloud-sdk-app-engine-go
  state: latest
- name: google-cloud-sdk-app-engine-python
  state: latest
- name: google-cloud-sdk-app-engine-python
  state: latest
- name: kubectl
  state: latest
- name: docker-ce
  state: latest
- name: docker-ce-cli
  state: latest
- name: containerd.io
  state: latest
- name: ctop
  state: latest
- name: terraform
  state: latest
