steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['shellscript/delete_template_instances.bash']
  env:
  - 'ZONE=${_ZONE}'
  timeout: 120s

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['shellscript/fetch_service_account_file.bash']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['shellscript/fetch_ssh_private_key.bash']

- name: 'hashicorp/terraform'
  id: 'terraform-init'
  args:
  - init
  timeout: 10s

- name: 'hashicorp/terraform'
  id: 'terraform-plan'
  args:
  - plan
  - -var=distribution=${_DISTRIBUTION}
  waitFor:
  - 'terraform-init'
  timeout: 10s

- name: 'hashicorp/terraform'
  id: 'terraform-apply'
  args:
  - apply
  - -auto-approve
  waitFor:
  - 'terraform-plan'
  timeout: 120s

- name: 'gcr.io/${PROJECT_ID}/ansible'
  id: 'ansible-execution'
  entrypoint: '/bin/bash'
  args: ['shellscript/run-ansible.bash']
  waitFor:
  - 'terraform-apply'
  timeout: 3600s

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'create-machine-image'
  entrypoint: 'bash'
  args: ['shellscript/create_image_from_instance.bash']
  env:
  - DISTRIBUTION=${_DISTRIBUTION}
  - REVISION=${_REVISION}
  - ZONE=${_ZONE}
  waitFor:
  - 'ansible-execution'
  timeout: 600s

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'delete-running-tempalte-instance'
  entrypoint: 'bash'
  args: ['shellscript/delete_template_instances_and_old_machine_images.bash']
  env:
  - ZONE=${_ZONE}
  waitFor:
  - 'create-machine-image'
  timeout: 120s

substitutions:
  _ZONE: asia-northeast1-a
  _DISTRIBUTION: debian
  _REVISION: ${SHORT_SHA}

timeout: 5400s
