---
- name: Install preconditional apt packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ precondition_apt_packages }}"
  become: yes

- name: Install external apt repository PGP keys
  ansible.builtin.apt_key:
    url: "{{ item.url }}"
    keyring: "{{ item.keyring }}"
  with_items: "{{ pgp_keys }}"
  become: yes

- name: Add external apt repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ debian_10_apt_repositories }}"
  become: yes

- name: Update apt repositories
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install basic apt packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ basic_apt_packages }}"
  become: yes