---
# Go version
go_version: 1.16

symbolic_links:
- src: ~/.dotfiles/.zshrc
  dest: ~/.zshrc
- src: ~/.dotfiles/.zshenv.linux
  dest: ~/.zshenv
- src: ~/.dotfiles/.emacs.d
  dest: ~/.emacs.d
- src: ~/.dotfiles/.tmux.conf.linux
  dest: ~/.tmux.conf
