---
# Go
# https://golang.org/dl/
go_install_version: 1.16.6
go_tarball_checksum: "sha256:be333ef18b3016e9d7cb7b1ff1fdb0cac800ca0be4cf2290fe613b3d069dfe0d"
goroot: "/home/{{ ansible_env.USER }}/.go"
gopath: "/home/{{ ansible_env.USER }}/go"

# Java
java_version: 15
openjdk_tarball: https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x64_linux_hotspot_15.0.2_7.tar.gz

# Kotlin
# https://kotlinlang.org/docs/releases.html#release-details
kotlin_version: 1.5.21
kotlin_tarball: "https://github.com/JetBrains/kotlin/releases/download/v{{ kotlin_version }}/kotlin-native-linux-{{ kotlin_version }}.tar.gz"

# Node
# https://nodejs.org/en/download/
node_version: 14.17.3

# Ruby
# https://www.ruby-lang.org/en/downloads/
ruby_version: 2.7.4
rbenv_path: ~/.rbenv/bin/rbenv

# gcloud
# https://cloud.google.com/sdk/docs/release-notes
gcloud_version: 348.0.0
gcloud_tarball: "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ gcloud_version }}-linux-x86_64.tar.gz"
gcloud_dir: ~/.google-cloud-sdk
gcloud_components:
- beta
- alpha
- gsutil
- app-engine-go
- app-engine-python
- app-engine-python-extras
- kubectl
- skaffold
- kustomize

symbolic_links:
- src: ~/.dotfiles/starship.toml
  dest: ~/.config/starship.toml
- src: ~/.dotfiles/.zshrc
  dest: ~/.zshrc
- src: ~/.dotfiles/.zshenv.linux
  dest: ~/.zshenv
- src: ~/.dotfiles/.emacs.d
  dest: ~/.emacs.d
- src: ~/.dotfiles/.tmux.conf.linux
  dest: ~/.tmux.conf
- src: ~/.dotfiles/.Xresources
  dest: ~/.Xresources

github_tarball_releases:
- repo: peco/peco
  version: v0.5.10
  asset: peco_linux_amd64.tar.gz
  extra_opts: ["--strip-components=1"]
- repo: grafana/k6
  version: v0.33.0
  asset: k6-v0.33.0-linux64.tar.gz
  extra_opts: ["--strip-components=1"]
- repo: gohugoio/hugo
  version: v0.85.0
  asset: hugo_0.85.0_Linux-64bit.tar.gz
  extra_opts: []
