---
- name: Install Go
  import_role:
    name: fubarhouse.golang
  vars:
    go_version: "{{ go_install_version }}"
    GOPATH: "{{ goroot }}"
    GOROOT: "{{ gopath }}"
    GOPROXY: https://proxy.golang.org
    GO111MODULE: "on"
    GOOS: linux
    GOARCH: amd64
    mode_codebase: 0755
    go_checksum: "{{ go_tarball_checksum }}"
    go_get:
    - name: dlv
      url: github.com/go-delve/delve/cmd/dlv
      modules: true
    - name: lazydocker
      url: github.com/jesseduffield/lazydocker
      modules: true
  become: yes
  tags:
  - go

- name: Change permission of GOROOT
  ansible.builtin.file:
    path: "{{ goroot }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    recurse: yes
  become: yes
  tags:
  - go

- name: Change permission of GOPATH
  ansible.builtin.file:
    path: "{{ gopath }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    recurse: yes
  become: yes
  tags:
  - go