---
- name: Create directory for venv pool
  ansible.builtin.file:
    path: ~/python
    state: directory
    mode: 0755

- name: Get the status of Python venv root directory
  ansible.builtin.stat:
    path: ~/python
  register: venv_root

- name: Copy requirements.txt
  ansible.builtin.template:
    src: requirements.txt
    dest: "{{ venv_root.stat.path }}/requirements.txt"
  when: venv_root.stat.exists

- name: Confirm the existance of requirements.txt
  ansible.builtin.stat:
    path: "{{ venv_root.stat.path }}/requirements.txt"
  register: requirements_file

- name: Update pip in misc venv
  ansible.builtin.pip:
    name: pip
    state: latest
    virtualenv: "{{ venv_root.stat.path }}/misc"
    virtualenv_command: "/usr/bin/python3 -m venv"
  when: venv_root.stat.exists

- name: Install Python packages into misc venv
  ansible.builtin.pip:
    requirements: "{{ requirements_file.stat.path }}"
    virtualenv: "{{ venv_root.stat.path }}/misc"
    virtualenv_command: "/usr/bin/python3 -m venv"
  when: venv_root.stat.exists

