---
arch_packages:
- name: ca-certificates
  state: latest
- name: ca-certificates-mozilla
  state: latest
- name: gnupg
  state: latest
- name: unzip
  state: latest
- name: wget
  state: latest
- name: curl
  state: latest
- name: git
  state: latest
- name: zsh
  state: latest
- name: base-devel
  state: latest
- name: emacs
  state: latest
- name: vim
  state: latest
- name: python3
  state: latest
- name: python3-pip
  state: latest
- name: python3-venv
  state: latest
- name: tmux
  state: latest
- name: jq
  state: latest
- name: the_silver_searcher
  state: latest
- name: docker
  state: latest
- name: trizen
  state: latest

gcloud_packages:
- name: google-cloud-sdk
  state: latest
- name: google-cloud-sdk-app-engine-go
  state: latest
- name: google-cloud-sdk-app-engine-python
  state: latest
- name: google-cloud-sdk-app-engine-python
  state: latest
- name: kubectl
  state: latest
