---
- name: Reinstall archilinux-keyring package
  community.general.pacman:
    name: archlinux-keyring
    state: latest
  become: yes

- name: packman-key refresh
  ansible.builtin.shell:
    cmd: pacman-key --refresh-keys
  become: yes

- name: pacman-key populate
  ansible.builtin.shell:
    cmd: pacman-key --populate archlinux
  become: yes

- name: Update pacman cache
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Install arch packages
  community.general.pacman:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ arch_packages }}"
  become: yes

- name: Install trizen
  aur:
    name: trizen
    use: makepkg
    state: latest

